backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "fishing-report" # Used in routes, e.g., /admin/collections/blog
    label: "釣果報告" # Used in the UI
    folder: "collections/_fishing-report" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "記事のタイトル", name: "title", widget: "string" }
      - { label: "記事のカテゴリー", name: "categories", widget: "select", options: { label: "釣果報告", value: "fishig-report" } }
      - { label: "記事のタイプ", name: "header_type", widget: "select", options: { label: "ポスト", value: "post" } }
      - { label: "記事のタグ", name: "tags", widget: "select", multiple: true, min: 1, max: 3, options: ["釣果", "釣果報告", "船"], default: ["釣果", "釣果報告", "船"] }
      - { label: "掲載日", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }