backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "fishing-report" # Used in routes, e.g., /admin/collections/blog
    label: "釣果報告" # Used in the UI
    folder: "collections/_fishing-report" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "カテゴリー", name: "categories", widget: "select", options: [ { label: "釣果報告", value: "fishig-report" } ] }
      - { label: "レイアウトテンプレート", name: "header_type", widget: "hidden", default: "post"}
      - { label: "タグ", name: "tags", widget: "select", multiple: true, min: 1, max: 3, options: ["釣果", "釣果報告", "船"], default: ["釣果"] }
      - { label: "掲載日", name: "date", widget: "datetime" }
      - { label: "日付を表示", name: "show_date", widget: "boolean", default: true}
      - { label: "タグを表示", name: "show_tags", widget: "boolean", default: true}
      - { label: "カテゴリーを表示", name: "show_categories", widget: "boolean", default: true}
      - { label: "著者名を表示", name: "show_author", widget: "boolean", default: true}
      - { label: "本文", name: "body", widget: "markdown" }