source 'https://rubygems.org'
gem "jekyll", "=3.9.3"
gem 'jekyll-redirect-from'
gem 'github-pages', group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.0'
  gem 'jekyll-github-metadata'
  gem 'jekyll-sitemap'
  gem 'jekyll-include-cache'
end

gem 'wdm', '>= 0.1.0', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "webrick"
gem 'faraday-retry'
gem 'tzinfo-data'
gem 'jekyll-robotstxt', '~> 0.3.2'